### Numpy : Package for Mutidimensional array

In [1]:
import numpy as np

In [3]:
simple_list= [6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([6,7,9])
arr

array([6, 7, 9])

In [6]:
list_of_lists=([1,2,3],[4,5,6])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arra=np.array([[1,2,3],[4,5,6],[7,8,9]])
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(3,11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(3,11,3)

array([3, 6, 9])

In [15]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [21]:
np.ones((2,5),dtype=int) # form an 2 by 5 array of ones 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.linspace(0,1,5) # 5 equally spaced numbers from 0 to 1 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.linspace(0,20,10) #10 equally spaced numbers from 0 to 20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [24]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [25]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(2,4) # uniform distributuion b/w 0 to 1

array([[0.34994386, 0.94367528, 0.20570297, 0.09033698],
       [0.26771535, 0.37699829, 0.26152734, 0.29505032]])

In [27]:
np.random.randn(2,4)

array([[-1.05102476, -0.87772275, -0.06413595,  0.54665335],
       [-0.26689319, -1.34285218, -0.29276164,  0.35027126]])

In [28]:
np.random.randint(0,10,100)

array([5, 0, 3, 0, 5, 6, 0, 5, 0, 3, 8, 2, 9, 2, 9, 3, 3, 8, 1, 2, 6, 0,
       0, 8, 6, 8, 8, 2, 2, 3, 8, 4, 5, 6, 8, 6, 2, 1, 3, 9, 3, 4, 0, 7,
       6, 9, 7, 4, 4, 1, 4, 6, 9, 3, 5, 7, 5, 3, 7, 0, 2, 6, 7, 8, 0, 3,
       1, 7, 8, 9, 2, 7, 4, 3, 1, 6, 2, 3, 3, 5, 3, 5, 6, 7, 3, 8, 5, 9,
       6, 7, 8, 2, 7, 5, 0, 4, 0, 3, 7, 9])

In [29]:
np.random.randint(10,100,15)

array([31, 16, 96, 61, 55, 46, 45, 71, 12, 70, 49, 90, 52, 32, 95])

In [30]:
np.random.randint(20,56,100)

array([33, 23, 33, 39, 22, 41, 24, 24, 30, 45, 42, 33, 30, 22, 41, 38, 43,
       24, 42, 55, 38, 37, 43, 31, 39, 40, 29, 32, 22, 31, 41, 37, 43, 37,
       42, 33, 23, 26, 41, 23, 35, 21, 51, 35, 54, 52, 29, 51, 31, 37, 42,
       32, 22, 50, 41, 39, 45, 33, 38, 36, 48, 55, 47, 55, 43, 43, 22, 36,
       51, 28, 50, 26, 36, 50, 31, 49, 45, 41, 41, 37, 20, 30, 41, 36, 39,
       22, 34, 36, 49, 42, 40, 47, 51, 32, 24, 43, 33, 22, 35, 25])

In [32]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [34]:
rand_array=np.random.randint(0,10,5)
rand_array

array([2, 4, 4, 4, 6])

In [35]:
sample_array.min()

2

In [36]:
sample_array.argmin()

0

In [37]:
rand_array.argmin()

0

In [38]:
rand_array.max()

6

In [39]:
rand_array.argmax()

4

In [40]:
sample_array.argmax()

17

In [41]:
sample_array.dtype

dtype('int32')

In [43]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
a=np.random.rand(2,3)
a

array([[0.9322307 , 0.93416872, 0.52745949],
       [0.0125872 , 0.03067461, 0.67228513]])

In [47]:
a.T

array([[0.9322307 , 0.0125872 ],
       [0.93416872, 0.03067461],
       [0.52745949, 0.67228513]])

In [49]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [53]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [55]:
sample_array[5]=100
sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [56]:
sample_array[1:12]

array([[ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [57]:
sample_array[3:9]

array([[ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [59]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [60]:
sample_array[:]=1001
sample_array

array([[1001, 1001, 1001],
       [1001, 1001, 1001],
       [1001, 1001, 1001],
       [1001, 1001, 1001],
       [1001, 1001, 1001],
       [1001, 1001, 1001]])